CREATE DATABASE IF NOT EXISTS DBAuth CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS DBBook CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS DBBorrow CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS DBFine CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS DBNotification CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'booksphere'@'%' IDENTIFIED BY 'booksphere123';

GRANT ALL PRIVILEGES ON DBAuth.* TO 'booksphere'@'%';
GRANT ALL PRIVILEGES ON DBBook.* TO 'booksphere'@'%';
GRANT ALL PRIVILEGES ON DBBorrow.* TO 'booksphere'@'%';
GRANT ALL PRIVILEGES ON DBFine.* TO 'booksphere'@'%';
GRANT ALL PRIVILEGES ON DBNotification.* TO 'booksphere'@'%';

FLUSH PRIVILEGES;
